spring:
  application:
    name: ctp-backend-assignment-sandbox
  datasource:
    url: ${DB_URL}
    driverClassName: org.h2.Driver
    username: ${H2_USER}
    password: ${H2_PASSWORD}
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
      minimumIdle: 1
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    show-sql: false
    sql:
      init:
        mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

logging:
  level:
    org:
      springframework: INFO
    kotlin:
      com:
        ahold: DEBUG

server:
  port: 8080

swagger:
  api:
    title: Delivery System
    description: APIs for Delivery System
    version: 1.0
    contact:
      name: Abdul Adoni